name = "r2"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pusat"   # <-- Ganti dengan nama bucket kamu

# Opsional: Tambahkan secret untuk autentikasi API
# [vars]
# AUTH_TOKEN = "your-secret-token"
